const IP_API_GET_LOCATION_ERROR = "IP_API_GET_LOCATION_ERROR"
const WEATHER_API_GET_CURRENT_WEATHER_ERROR = "WEATHER_API_GET_CURRENT_WEATHER_ERROR"
const WEATHER_API_GET_FORECAST_WEATHER_ERROR = "WEATHER_API_GET_FORECAST_WEATHER_ERROR"
const WEATHER_API_GET_CITY_LOCATION_ERROR = "WEATHER_API_GET_CITY_LOCATION_ERROR"


const codeErrors = {
	IP_API_GET_LOCATION_ERROR,
	WEATHER_API_GET_CURRENT_WEATHER_ERROR,
	WEATHER_API_GET_FORECAST_WEATHER_ERROR,
	WEATHER_API_GET_CITY_LOCATION_ERROR
}

module.exports = {
	codeErrors
}